# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '11.0'

  pod 'LookinServer'
  pod 'SDWebImage'
  pod 'YYImage', :git => 'https://github.com/QiuYeHong90/YYImage.git'
  #pod 'RXCPageView', :path=> '../'

end
